
server
{
	listen 0.0.0.0 80;

	serverName server1;

	clientMaxBodySize 1048576; #1mb

	errorPage 404 server1_404.html;

	location /cgi
	{
		cgi .py python3;
		methods GET POST DELETE;
	}

	location /upload
	{
		clientMaxBodySize 10485760; #10mb
		uploadDir /uploads;
		methods POST;
	}

	location /
	{
		root /html;
		index index.html;
		autoIndex off;
	}

	location /obsoleteUrl
	{
		redirect 301 /html/index.html;
	}
}

server
{
	listen 0.0.0.0 80;

	serverName server2;

	root /html2;
	index index.html;
	autoIndex off;

	clientMaxBodySize 1048576; #1mb

	errorPage 404 server2_404.html;

	location /cgi
	{
		cgi .py python3;
		methods GET POST DELETE;
	}

	location /upload
	{
		clientMaxBodySize 10485760; #10mb
		uploadDir /uploads;
		methods POST;
	}

	location /obsoleteUrl
	{
		redirect 301 /html2/index.html;
	}
}
